<?xml version="1.0" encoding="utf-8"?><Database Name="FptApt_001" Class="StudentDataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-GQ6T9MQ;Initial Catalog=FptApt_001;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="FptApt_001ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Student" Member="Students">
    <Type Name="Student">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="FirstMidName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="EnrollmentDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Phone" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>