// <auto-generated />
namespace ManagerProduct.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _09212020_newMG111 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_09212020_newMG111));
        
        string IMigrationMetadata.Id
        {
            get { return "202012180422350_09212020_newMG111"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
