//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestConsumerAs2.TypeBlogServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TypeBlog", Namespace="http://schemas.datacontract.org/2004/07/WebServiceAssigment2.Models.DataModels")]
    [System.SerializableAttribute()]
    public partial class TypeBlog : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestConsumerAs2.TypeBlogServiceReference.Blog[] BlogsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestConsumerAs2.TypeBlogServiceReference.Blog[] Blogs {
            get {
                return this.BlogsField;
            }
            set {
                if ((object.ReferenceEquals(this.BlogsField, value) != true)) {
                    this.BlogsField = value;
                    this.RaisePropertyChanged("Blogs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descriptions {
            get {
                return this.DescriptionsField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionsField, value) != true)) {
                    this.DescriptionsField = value;
                    this.RaisePropertyChanged("Descriptions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeName {
            get {
                return this.TypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeNameField, value) != true)) {
                    this.TypeNameField = value;
                    this.RaisePropertyChanged("TypeName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Blog", Namespace="http://schemas.datacontract.org/2004/07/WebServiceAssigment2.Models.DataModels")]
    [System.SerializableAttribute()]
    public partial class Blog : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentShortField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TypeBlogIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int viewsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContentShort {
            get {
                return this.ContentShortField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentShortField, value) != true)) {
                    this.ContentShortField = value;
                    this.RaisePropertyChanged("ContentShort");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Created {
            get {
                return this.CreatedField;
            }
            set {
                if ((this.CreatedField.Equals(value) != true)) {
                    this.CreatedField = value;
                    this.RaisePropertyChanged("Created");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Place {
            get {
                return this.PlaceField;
            }
            set {
                if ((object.ReferenceEquals(this.PlaceField, value) != true)) {
                    this.PlaceField = value;
                    this.RaisePropertyChanged("Place");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TypeBlogID {
            get {
                return this.TypeBlogIDField;
            }
            set {
                if ((this.TypeBlogIDField.Equals(value) != true)) {
                    this.TypeBlogIDField = value;
                    this.RaisePropertyChanged("TypeBlogID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int views {
            get {
                return this.viewsField;
            }
            set {
                if ((this.viewsField.Equals(value) != true)) {
                    this.viewsField = value;
                    this.RaisePropertyChanged("views");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TypeBlogServiceReference.ITypeBlogService")]
    public interface ITypeBlogService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITypeBlogService/GetTypeBlogList", ReplyAction="http://tempuri.org/ITypeBlogService/GetTypeBlogListResponse")]
        TestConsumerAs2.TypeBlogServiceReference.TypeBlog[] GetTypeBlogList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITypeBlogService/GetTypeBlogList", ReplyAction="http://tempuri.org/ITypeBlogService/GetTypeBlogListResponse")]
        System.Threading.Tasks.Task<TestConsumerAs2.TypeBlogServiceReference.TypeBlog[]> GetTypeBlogListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITypeBlogService/AddTypeBlog", ReplyAction="http://tempuri.org/ITypeBlogService/AddTypeBlogResponse")]
        void AddTypeBlog(TestConsumerAs2.TypeBlogServiceReference.TypeBlog typeBlog);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITypeBlogService/AddTypeBlog", ReplyAction="http://tempuri.org/ITypeBlogService/AddTypeBlogResponse")]
        System.Threading.Tasks.Task AddTypeBlogAsync(TestConsumerAs2.TypeBlogServiceReference.TypeBlog typeBlog);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITypeBlogService/GetTypeBlogById", ReplyAction="http://tempuri.org/ITypeBlogService/GetTypeBlogByIdResponse")]
        TestConsumerAs2.TypeBlogServiceReference.TypeBlog GetTypeBlogById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITypeBlogService/GetTypeBlogById", ReplyAction="http://tempuri.org/ITypeBlogService/GetTypeBlogByIdResponse")]
        System.Threading.Tasks.Task<TestConsumerAs2.TypeBlogServiceReference.TypeBlog> GetTypeBlogByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITypeBlogService/UpdateTypeBlog", ReplyAction="http://tempuri.org/ITypeBlogService/UpdateTypeBlogResponse")]
        void UpdateTypeBlog(TestConsumerAs2.TypeBlogServiceReference.TypeBlog typeBlog);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITypeBlogService/UpdateTypeBlog", ReplyAction="http://tempuri.org/ITypeBlogService/UpdateTypeBlogResponse")]
        System.Threading.Tasks.Task UpdateTypeBlogAsync(TestConsumerAs2.TypeBlogServiceReference.TypeBlog typeBlog);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITypeBlogServiceChannel : TestConsumerAs2.TypeBlogServiceReference.ITypeBlogService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TypeBlogServiceClient : System.ServiceModel.ClientBase<TestConsumerAs2.TypeBlogServiceReference.ITypeBlogService>, TestConsumerAs2.TypeBlogServiceReference.ITypeBlogService {
        
        public TypeBlogServiceClient() {
        }
        
        public TypeBlogServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TypeBlogServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TypeBlogServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TypeBlogServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TestConsumerAs2.TypeBlogServiceReference.TypeBlog[] GetTypeBlogList() {
            return base.Channel.GetTypeBlogList();
        }
        
        public System.Threading.Tasks.Task<TestConsumerAs2.TypeBlogServiceReference.TypeBlog[]> GetTypeBlogListAsync() {
            return base.Channel.GetTypeBlogListAsync();
        }
        
        public void AddTypeBlog(TestConsumerAs2.TypeBlogServiceReference.TypeBlog typeBlog) {
            base.Channel.AddTypeBlog(typeBlog);
        }
        
        public System.Threading.Tasks.Task AddTypeBlogAsync(TestConsumerAs2.TypeBlogServiceReference.TypeBlog typeBlog) {
            return base.Channel.AddTypeBlogAsync(typeBlog);
        }
        
        public TestConsumerAs2.TypeBlogServiceReference.TypeBlog GetTypeBlogById(int id) {
            return base.Channel.GetTypeBlogById(id);
        }
        
        public System.Threading.Tasks.Task<TestConsumerAs2.TypeBlogServiceReference.TypeBlog> GetTypeBlogByIdAsync(int id) {
            return base.Channel.GetTypeBlogByIdAsync(id);
        }
        
        public void UpdateTypeBlog(TestConsumerAs2.TypeBlogServiceReference.TypeBlog typeBlog) {
            base.Channel.UpdateTypeBlog(typeBlog);
        }
        
        public System.Threading.Tasks.Task UpdateTypeBlogAsync(TestConsumerAs2.TypeBlogServiceReference.TypeBlog typeBlog) {
            return base.Channel.UpdateTypeBlogAsync(typeBlog);
        }
    }
}
