//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoVsAzuze.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int ID { get; set; }
        public System.DateTime Created { get; set; }
        public int Rate { get; set; }
        public string Content { get; set; }
        public int CustomerID { get; set; }
        public int BlogID { get; set; }
        public int ParentId { get; set; }
    
        public virtual Blog Blog { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
